apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-app-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: devops-app
  namespaceSelector:
    matchNames:
      - devops-app
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s
      scheme: http
      honorLabels: true
      metricRelabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: environment
          replacement: production
